export const GET_ALL_CONTACTS = 'GET_ALL_CONTACTS';
export const ADD_CONTACT = 'ADD_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const CONTACT_ERROR = 'CONTACT_ERROR';
export const SET_CURRENT = 'SET_CONTACT';
export const CLEAR_CURRENT = 'CLEAR_CONTACT';
export const FILTER_CONTACTS = 'FILTER_CONTATS';
export const CLEAR_FILTER = 'CLEAR_FILTER';

export const SET_ALERT = 'SET_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const USER_LOADED = 'USER_LOADED';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_LOADING = 'SET_LOADING';
